### ISSUE TITLE
使用update-sp修改詞的註音

### ISSUE THREAD

**Issue by RomaYun323** [ksqsf/rime-moran#46]
您好，我將pinyin.txt一些字的詞頻根據台灣(我個人)的發音習慣修改
例如：
謔 xue --> nue (台灣發音)，我將nue和xue的詞頻互換，修改其他含有謔的詞

使用`update-char-weight`調整`moran.chars.dict.yaml`詞頻
但在用`update-sp`轉換`moran.essay.dict.yaml`時，修改的註音並沒有被套用在`moran.essay.dict.yaml`

**Comment by ksqsf** [comment]
`update-sp` 是進行全字匹配，所以如果要替換詞語，就需要把整個詞語的讀音寫進去。如果 pinyin.txt 中不含有對應的詞語，則會使用 pypinyin 庫給詞語註音，而這個庫會使用大陸讀音。

具體來說，比如您可以把 pinyin.txt 拷貝到 pinyin_tw.txt，把其中的「戲謔」改成 nue，

```
戲謔	xi nue	746
```

然後用下面的命令就可以替換 essay 表中的讀音，

```
python3 schemagen.py --pinyin-table=pinyin_tw.txt update-sp --rime-dict=../moran.essay.dict.yaml --find=謔   # 只修改含有「謔」字的詞語
```

**Comment by RomaYun323** [comment]
有將註音都改了，輸入
```
python3 schemagen.py --pinyin-table=pinyin_tw.txt update-sp --rime-dict=../moran.essay.dict.yaml --find=血曝壑蝸淆崖暫酵攜賜堤垃圾懾挾謅驟隼謔擷拎劊檜圳卡艘謔
```
出現
```
Traceback (most recent call last):
  File "/home/a/tools/schemagen.py", line 637, in <module>
    handle_update_sp()
  File "/home/a/tools/schemagen.py", line 483, in handle_update_sp
    initialize_pinyin_table(skip_no_pinyin=True)
  File "/home/a/tools/schemagen.py", line 100, in initialize_pinyin_table
    with open(args.pinyin_table, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'pinyin_tw.txt'
```
pinyin不改名的話不會報錯，但讀音還是沒變
我將所有含「血 xue」的發音刪除後，結果也是一樣

**Comment by ksqsf** [comment]
`--pinyin-table` 的參數需要指向對應的文件，如果和 pinyin.txt 同級的話應該是用

```
--pinyin-table=./data/pinyin_tw.txt
```

**Comment by RomaYun323** [comment]
成功了，感謝。
